### PR TITLE
fix(mobile): stop crashing on launch when a thread has a PR stack

### PR DESCRIPTION
**Pull request by juliusmarminge**
Every 1.1.1 (55) TestFlight crash log in the last batch is the same trace: RN raised a fatal JS exception during the first render and expo-updates' `ErrorRecovery` aborted the process ~1 s after launch. That includes the launches started by the share extension, which is why sharing looked broken.

`resolveThreadCurrentPullRequest` in `packages/shared` called `Array#toReversed`, which Hermes does not implement. The mobile home list runs it for every thread's PR badge, so any environment with more than one open linked PR (a stack) threw on every cold launch. Introduced in #10839; #11233 fixed the same class of bug in two other files but missed this one.

- Copy and reverse instead.
- Run `threadPullRequests.test.ts` with `toSorted`/`toReversed`/`toSpliced` deleted from `Array.prototype`, like Hermes.
- Add an oxlint rule (`t3code/no-hermes-unsupported-array-methods`) applied to every package that ships to mobile (`apps/mobile`, `packages/shared`, `packages/client-runtime`, `packages/contracts`, non-test files) so the next one fails lint instead of TestFlight. The rule flags exactly the one shipping call and nothing else.

## Verification

Not a visual change. `vp test run packages/shared/src/threadPullRequests.test.ts` with the Hermes shim, against the `main` implementation vs this branch:

```
# before (main's threadPullRequests.ts, Hermes shim active)
 FAIL  resolveThreadCurrentPullRequest > reports a stack when several links are open and puts the highest layer on top
 TypeError: chain.layers.toReversed is not a function
 FAIL  resolveThreadCurrentPullRequest > orders an open set without stack data by most recent link
 TypeError: chain.layers.toReversed is not a function
 Failed Tests 4

# after
 Tests  33 passed (33)
```

`vp test run oxlint-plugin-t3code/rules/no-hermes-unsupported-array-methods.test.ts` passes (7 cases). `tsc --noEmit` clean for `packages/shared`.

Claude Fable 5 via Claude Code.

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved mobile runtime compatibility when ordering pull-request stack layers by using supported array operations.
  * Added lint errors for unsupported `toSorted`, `toReversed`, and `toSpliced` usage in Hermes-targeted code, including common property-access patterns.

* **Tests**
  * Added coverage for supported alternatives and unsupported array-method usage.
  * Added isolated test coverage for environments without ES2023 array methods.

### CODE REVIEW

File: oxlint-plugin-t3code/rules/no-hermes-unsupported-array-methods.ts [hunk 1]
```diff
@@ -0,0 +1,42 @@
+import { defineRule } from "@oxlint/plugins";
+
+// ES2023 change-array-by-copy methods. Hermes does not implement them, and
+// tsconfig targets ESNext, so nothing but this rule stands between a call and a
+// TypeError that is fatal on every mobile launch that reaches it.
+const UNSUPPORTED_METHODS = new Map([
+  ["toSorted", "[...array].sort(...)"],
+  ["toReversed", "[...array].reverse()"],
+  ["toSpliced", "[...array].splice(...)"],
```
[the remark this answers is not in the document]
Comment (juliusmarminge) [reply oxlint-plugin-t3code/rules/no-hermes-unsupported-array-methods.ts]: Fixed in aac6d0a37eff7ad467b946fc0c6c7135feb2cbf7: the toSpliced remediation now reads `const copy = [...array]; copy.splice(...); use copy`, and the test asserts that text.

File: oxlint-plugin-t3code/rules/no-hermes-unsupported-array-methods.ts [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+    return {
+      CallExpression(node) {
+        if (node.callee.type !== "MemberExpression") return;
+        const { property } = node.callee;
+        const name =
+          property.type === "Identifier"
+            ? property.name
+            : property.type === "Literal" && typeof property.value === "string"
+              ? property.value
+              : null;
```
[the remark this answers is not in the document]
Comment (juliusmarminge) [reply oxlint-plugin-t3code/rules/no-hermes-unsupported-array-methods.ts]: Fixed in aac6d0a37eff7ad467b946fc0c6c7135feb2cbf7: no-substitution template-literal property names are extracted (cooked value of the single quasi); template literals with substitutions stay ignored. Fixtures added for both.
